# Site settings
title: Icaro Caldeira Carreira
email: icaro.caldeira@hotmail.com
description: Aprendendo e compartilhando conhecimento
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://icarcal.github.io" # the base hostname & protocol for your site
twitter_username: icarcal
github_username:  icarcal

# Build settings
markdown: kramdown
exclude: [vendor, node_modules]

defults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      posttitle: ""